nav_points: [
  {x: 4.56, y: 0.83, theta: 3.14},
  {x: 3.10, y: 1.62, theta: 1.60},
  {x: 6.08, y: 5.34, theta: 0.00},
  {x: 6.17, y: 3.18, theta: 0.00},
  {x: 0.87, y: 9.12, theta: 1.90},
  {x: 3.03, y: 7.99, theta: 2.04},
  {x: 4.12, y: 8.01, theta: 2.12},
  {x: 2.96, y: 5.27, theta: 3.79},
  {x: 7.32, y: 7.92, theta: 1.71},
  {x: 0.92, y: 0.82, theta: 5.10},
  {x: 4.18, y: 2.01, theta: 4.81},
  {x: 8.39, y: 0.60, theta: 3.17},
  {x: 9.21, y: 5.77, theta: 1.19},
]
